packages:
  - 'web'
  - 'desktop'
  - 'packages/*'
allowBuilds:
  '@smithery/cli': false
  agent-browser: false
  better-sqlite3: true
  bufferutil: true
  cbor-extract: true
  cpu-features: false
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
  sharp: false
  ssh2: false
  utf-8-validate: true
