packages:
  - "desktop"
  - "packages/*"
  - "web"
  - "backend"
allowBuilds:
  '@google/genai': set this to true or false
  '@matrix-org/matrix-sdk-crypto-nodejs': set this to true or false
  '@smithery/cli': set this to true or false
  agent-browser: set this to true or false
  better-sqlite3: set this to true or false
  bufferutil: set this to true or false
  cbor-extract: set this to true or false
  cpu-features: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  node-pty: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  ssh2: set this to true or false
  utf-8-validate: set this to true or false
