/**
 * scripts/probe-chat-route.ts
 *
 * v4 — module-hooks-driven stub-loader probe. Validates the audit's
 * cumulative parallelization-savings estimate (~80-235ms/request per
 * /opt/bing/docs/async-parallelization-opportunities.md Top 5 Quick Wins
 * + Meta-coalesce audit NEW-1..NEW-4) against real-stub microbenchmarks
 * driven by Node Module hooks.
 *
 * Strategy (v4 upgrade from v3 synthesized-shape):
 *   1. Register probe-loader-hooks.mjs BEFORE any import that would
 *      otherwise load the real collaborators.
 *   2. Import probe-stub-manifest.ts (also intercepted by the loader for
 *      type-safety — its satisfies-clauses ensure compile-time parity
 *      with the real module exports).
 *   3. For each intercepted layer, call its primary fn (the audit-claimed
 *      upstream) K times SEQUENTIALLY vs K times in Promise.all(PARALLEL).
 *      The stub's taggedUpstream wrapping injects a synthetic per-call
 *      latency and emits an ALS timing tag, so per-upstream timings land
 *      in the report (not just outer wall-clock).
 *   4. Compute (seq - par) per layer as the parallelization saving.
 *   5. Compare against /opt/bing/docs/async-parallelization-opportunities.md
 *      audit claim per layer (low/high saved_ms range). Report within/
 *      BELOW/ABOVE per the audit estimate.
 *
 * VERSION 4: register-then-import. The hook must be installed before any
 * module that would otherwise resolve the intercepted specifiers.
 *
 * Run: pnpm tsx scripts/probe-chat-route.ts
 *      PROBE_N=200 pnpm tsx scripts/probe-chat-route.ts
 */

import { register } from 'node:module';
import { AsyncLocalStorage } from 'node:async_hooks';
import { performance } from 'node:perf_hooks';
import { writeFileSync } from 'node:fs';
import { setTimeout as sleep } from 'node:timers/promises';

// --------------------------------------------------------------------------
// 1. Register the loader hook BEFORE any subsequent import.
// --------------------------------------------------------------------------
//
// tsx installs its own loader for .ts → .js transpilation. Multiple
// loaders chain cleanly (per Node 22 / tsx docs). Our hook only short-
// circuits the specifiers listed in probe-stub-manifest.ts plus
// 'next/server'; everything else falls through to tsx + Node's defaults.

// `new URL(...)` returns a URL object whose `.href` is already a valid
// file:// URL — no need to re-wrap with pathToFileURL() (which expects a
// string path, not a URL object, hence `ERR_INVALID_ARG_TYPE`).
const HOOK_URL = new URL('./probe-loader-hooks.mjs', import.meta.url).href;
register(HOOK_URL, import.meta.url);

// --------------------------------------------------------------------------
// 2. Hook interface types — exported so the synthetic stubs generated
//    by probe-loader-hooks.mjs can call `taggedUpstream`.
// --------------------------------------------------------------------------

export interface UpstreamTag {
  layer: string;
  variant: 'sequential' | 'parallel';
  startMs: number;
  endMs: number;
}

export interface ProbeState {
  reqId: string;
  tags: UpstreamTag[];
}

export type Variant = 'sequential' | 'parallel';

const als = new AsyncLocalStorage<ProbeState>();

function recordTag(
  layer: string,
  variant: Variant,
  startMs: number,
  endMs: number,
): void {
  const ctx = als.getStore();
  if (ctx) ctx.tags.push({ layer, variant, startMs, endMs });
}

/**
 * taggedUpstream — exported so the synthetic stubs (generated by
 * probe-loader-hooks.mjs) can call this to emit per-upstream ALS timing.
 *
 * Args: (layer, variant, latencyMs, payload) — sleeps latencyMs then
 * returns payload and appends a per-upstream timing tag into the active
 * ALS scope's tags array.
 */
export async function taggedUpstream(
  layer: string,
  variant: Variant,
  latencyMs: number,
  payload: unknown,
): Promise<unknown> {
  const t0 = performance.now();
  await new Promise<unknown>((r) => setTimeout(() => r(payload), latencyMs));
  recordTag(layer, variant, t0, performance.now());
  return payload;
}

async function withRequest<T>(reqId: string, fn: () => Promise<T>): Promise<T> {
  return als.run({ reqId, tags: [] }, fn);
}

// --------------------------------------------------------------------------
// 3. Stats helpers
// --------------------------------------------------------------------------

function percentile(sorted: readonly number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = Math.max(
    0,
    Math.min(sorted.length - 1, Math.floor((p / 100) * (sorted.length - 1))),
  );
  return sorted[idx];
}

function summarize(layer: string, variant: Variant, samples: number[]) {
  const sorted = [...samples].sort((a, b) => a - b);
  const mean =
    samples.length > 0 ? samples.reduce((a, v) => a + v, 0) / samples.length : 0;
  return {
    layer,
    variant,
    samples: samples.length,
    min_ms: sorted[0] ?? 0,
    p50_ms: percentile(sorted, 50),
    p90_ms: percentile(sorted, 90),
    p99_ms: percentile(sorted, 99),
    max_ms: sorted[sorted.length - 1] ?? 0,
    mean_ms: mean,
  };
}

// --------------------------------------------------------------------------
// 4. Per-layer bench runner: K-sequential vs K-parallel
// --------------------------------------------------------------------------

interface LayerBenchShape {
  layer: string;
  primaryFn: (...args: unknown[]) => Promise<unknown>;
  K: number;
}

async function benchLayer(
  shape: LayerBenchShape,
  n: number,
): Promise<{ seq: ReturnType<typeof summarize>; par: ReturnType<typeof summarize> }> {
  const { layer, primaryFn, K } = shape;
  const args: unknown[] = [
    { query: 'probe-stub' },
    { userId: 'u_probe_stub_001' },
    null,
  ];

  // SEQUENTIAL: K await primaryFn() calls per iteration. Wall-clock
  // cost = K * latencyMs (each call has taggedUpstream sleeping latencyMs).
  const seqSamples: number[] = [];
  for (let i = 0; i < n; i++) {
    const t0 = performance.now();
    for (let k = 0; k < K; k++) {
      await primaryFn(...args);
    }
    seqSamples.push(performance.now() - t0);
    await sleep(2);
  }

  // PARALLEL: K primaryFn() calls in Promise.all per iteration. Wall-clock
  // cost = max(latencyMs) = latencyMs since all stub calls share the
  // same latency (sleep runs concurrently).
  const parSamples: number[] = [];
  for (let i = 0; i < n; i++) {
    const t0 = performance.now();
    await Promise.all(Array.from({ length: K }, () => primaryFn(...args)));
    parSamples.push(performance.now() - t0);
    await sleep(2);
  }

  return {
    seq: summarize(layer, 'sequential', seqSamples),
    par: summarize(layer, 'parallel', parSamples),
  };
}

// --------------------------------------------------------------------------
// 5. Main
// --------------------------------------------------------------------------

async function main(): Promise<void> {
  const N = parseInt(process.env.PROBE_N ?? '50', 10);
  const WARMUP = parseInt(process.env.PROBE_WARMUP ?? '10', 10);

  console.log('probe-chat-route v4 (module-hooks-driven stub-loader)');
  console.log(`  N=${N} samples per variant, warmup=${WARMUP} iterations`);
  console.log(`  audit estimate to validate: 80-235ms/request cumulative\n`);

  // Pull in the manifest (this would normally go through the loader too,
  // but probe-stub-manifest.ts is a manifest file tsx compiles to .js,
  // and the load() generator only intercepts paths in stubManifest).
  const { stubManifest, AUDIT_CLAIMS } = await import('./probe-stub-manifest.ts');

  // Resolve each intercepted specifier through Node's ESM resolver so the
  // loader hook intercepts and emits the LATENCY-INJECTED synthetic stub
  // module. The manifest.stubExports entries are PRE-injection raw stubs
  // (zero latency); only the LOADER's synthetic-source stubs carry the
  // taggedUpstream(...) wrap that injects audit-locked per-call latency
  // and emits ALS per-upstream tags.
  const layerShapes: LayerBenchShape[] = await Promise.all(
    (['NEW-1', 'NEW-2', 'Tier 1 #1', 'Tier 1 #3'] as const).map(async (layerKey) => {
      const entry = Object.values(stubManifest).find(
        (e) => e.layer === layerKey,
      );
      if (!entry) throw new Error(`No manifest entry for layer ${layerKey}`);
      const primaryExportName = Object.keys(entry.stubExports)[0];
      // Dynamic `import(specifier)` routes through the registered loader
      // hook — at this point the loader's `resolve()` short-circuits to
      // the synthetic-stub URL and `load()` returns the taggedUpstream-
      // wrapped source. The stubModule we get back is the POST-injection
      // latency-injected stub (NOT the manifest's pre-injection stub).
      const stubModule = (await import(entry.specifier)) as Record<string, unknown>;
      const primaryFn =
        (stubModule[primaryExportName] as (...args: unknown[]) => Promise<unknown>) ??
        (Object.values(stubModule).find(
          (v) => typeof v === 'function',
        ) as (...args: unknown[]) => Promise<unknown>);
      return {
        layer: layerKey,
        primaryFn,
        K: entry.parallelK,
      };
    }),
  );

  // Warmup. Exercises the stub chain so JIT / module-cache settle.
  console.log(`Warming up (${WARMUP} iterations per layer)...`);
  for (let i = 0; i < WARMUP; i++) {
    for (const shape of layerShapes) {
      for (let k = 0; k < shape.K; k++) {
        await shape.primaryFn({});
      }
      await Promise.all(
        Array.from({ length: shape.K }, () => shape.primaryFn({})),
      );
    }
  }
  console.log('  warmup complete.\n');

  // Timed runs.
  const reports: Array<{
    seq: ReturnType<typeof summarize>;
    par: ReturnType<typeof summarize>;
  }> = [];
  for (const shape of layerShapes) {
    process.stdout.write(`  ${shape.layer.padEnd(15)} ... `);
    await withRequest(shape.layer, async () => {
      const r = await benchLayer(shape, N);
      reports.push(r);
    });
    process.stdout.write('done\n');
  }

  // Per-layer diff + audit-claim-vs-measured + cumulative
  console.log('\n=== PER-LAYER DIFF ===');
  console.log(
    '  LAYER             | audit_claim_low/high | seq_p50 par_p50  Δp50 | seq_p90 par_p90  Δp90 | within?',
  );
  console.log('  ' + '-'.repeat(110));

  let cumP50 = 0;
  let cumP90 = 0;
  const perLayerAudit: Array<{
    layer: string;
    audit_saved_low_ms: number;
    audit_saved_high_ms: number;
    measured_saved_p50_ms: number;
    measured_saved_p90_ms: number;
    within: boolean;
  }> = [];

  for (const r of reports) {
    // Derive saved_ms per layer as (seq_p50 - par_p50) - the wallclock cost
    // eliminated by parallelization (the audit's "saved" metric).
    const dP50 = r.seq.p50_ms - r.par.p50_ms;
    const dP90 = r.seq.p90_ms - r.par.p90_ms;
    cumP50 += dP50;
    cumP90 += dP90;
    const claim = AUDIT_CLAIMS[r.seq.layer as keyof typeof AUDIT_CLAIMS];
    const lo = claim?.audit_saved_low_ms ?? 0;
    const hi = claim?.audit_saved_high_ms ?? 0;
    const within = dP50 >= lo && dP50 <= hi ? 'WITHIN' : dP50 < lo ? 'BELOW' : 'ABOVE';
    console.log(
      `  ${r.seq.layer.padEnd(17)} | ` +
        `${lo}-${hi} ms            | ` +
        `${r.seq.p50_ms.toFixed(2).padStart(7)} ${r.par.p50_ms.toFixed(2).padStart(7)}  ` +
        `${dP50.toFixed(2).padStart(5)} | ` +
        `${r.seq.p90_ms.toFixed(2).padStart(7)} ${r.par.p90_ms.toFixed(2).padStart(7)}  ` +
        `${dP90.toFixed(2).padStart(5)} | ${within}`,
    );
    perLayerAudit.push({
      layer: r.seq.layer,
      audit_saved_low_ms: lo,
      audit_saved_high_ms: hi,
      measured_saved_p50_ms: dP50,
      measured_saved_p90_ms: dP90,
      within: within === 'WITHIN',
    });
  }

  console.log('\n=== CUMULATIVE SAVINGS vs AUDIT ESTIMATE ===');
  console.log(`  measured cumulative p50:           ${cumP50.toFixed(2)}ms per request`);
  console.log(`  measured cumulative p90:           ${cumP90.toFixed(2)}ms per request`);
  console.log(`  audit estimate range:              80-235ms per request`);
  const cumInRange = cumP50 >= 80 && cumP50 <= 235;
  console.log(
    `  verdict cumulative p50:            ${
      cumInRange ? 'WITHIN RANGE' : cumP50 < 80 ? 'BELOW (audit overestimates)' : 'ABOVE (audit underestimates)'
    }`,
  );
  console.log(
    `  verdict cumulative p90:            ${
      cumP90 >= 80 && cumP90 <= 235 ? 'WITHIN RANGE' : cumP90 < 80 ? 'BELOW (audit overestimates)' : 'ABOVE (audit underestimates)'
    }`,
  );

  const cumulative = {
    layers: reports.flatMap((r) => [r.seq, r.par]),
    per_layer_audit_vs_measured: perLayerAudit,
    cumulative_savings_p50_ms: cumP50,
    cumulative_savings_p90_ms: cumP90,
    audit_estimate_low_ms: 80,
    audit_estimate_high_ms: 235,
    cumulative_within_audit_range: cumInRange,
    architecture: 'v4 module-hooks-driven stub-loader',
    run_env: {
      N,
      warmup: WARMUP,
      node_version: process.version,
      tsx_version: (process.versions as Record<string, string | undefined>).tsx ?? 'unknown',
    },
  };
  const reportPath = process.env.PROBE_REPORT_PATH ?? '/tmp/probe-chat-route.json';
  writeFileSync(reportPath, JSON.stringify(cumulative, null, 2));
  console.log(`\n  JSON report \u2192 ${reportPath}`);
}

main().catch((e) => {
  console.error('probe-chat-route failed:', e);
  process.exit(1);
});
