import { useState, useEffect, useCallback } from 'react';

export const FUNNY_STATEMENTS = [
  "Consulting the oracle...",
  "Asking the digital spirits...",
  "Convincing the AI to be helpful...",
  "Wrestling with algorithms...",
  "Feeding the hamsters...",
  "Untangling neural pathways...",
  "Negotiating with the model...",
  "Bribing the algorithm with tokens...",
  "Convincing silicon to think...",
  "Rounding up the digital cows...",
  "Herding mathematical cats...",
  "Teaching neurons to dance...",
  "Debugging the existential dread...",
  "Consulting the rubber duck...",
  "Waiting for electrons to decide...",
  "Asking the cloud to think harder...",
  "Convincing bits to flip the right way...",
  "Polishing the neural weights...",
  "Asking ChatGPT for advice...",
  "Googling how to Google...",
  "Convincing the GPU to care...",
  "Translating human to robot...",
  "Explaining sarcasm to the AI...",
  "Teaching the model common sense...",
  "Convincing code to compile...",
  "Asking the internet to wait...",
  "Buffering brilliance...",
  "Loading genius modules...",
  "Defragmenting creativity...",
  "Optimizing the magic...",
  "Convincing the cloud it's not on fire...",
  "Asking the algorithm to try again...",
  "Translating coffee to code...",
  "Convincing the compiler this is fine...",
  "Asking Stack Overflow for help...",
  "Convincing the AI it's not alone...",
  "Teaching the model to care...",
  "Debugging reality...",
  "Convincing the void to respond...",
  "Asking the matrix for permission...",
  // Black culture & suave comedy additions
  "Askin' the algorithm if it got insurance for this computation...",
  "Tellin' the GPU to stop playin' and calculate...",
  "Convincin' the code to act right...",
  "Askin' Siri for the recipe...",
  "Tellin' Alexa to hush while we work...",
  "Convincin' the WiFi to catch this signal...",
  "Askin the cloud if it got a coupon for this processing...",
  "Tellin' the processor to stop draggin feet...",
  "Convincing the RAM to remember what it supposed to do",
  "Askin Google if they got a scholarship for this AI...",
  "Tellin' the algorithm to comb its hair and act presentable...",
  "Convincin' the database to spill the tea...",
  "Askin the server if it went to church this Sunday...",
  "Tellin' the cache to clean up its act...",
  "Convincin' the bandwidth to stretch a little further...",
  "Askin the firewall if we can get a family discount...",
  "Tellin' the CPU to stop sweatin' the small stuff...",
  "Convincin' the hard drive to hold onto this memory...",
  "Askin the keyboard if it ready for this conversation...",
  "Telling da mouse to click with some confidence...",
  "Convincin' the monitor to show its true colors...",
  "Askin the printer if it finally wanna work today...",
  "Tellin the software to update its wardrobe...",
  "Convincin' the browser to open more than one tab at a time...",
  "Askin the password if it forgot who run this account...",
  "Tellin' the encryption to keep this between us...",
  "Convincin' the download to finish before the next generation...",
  "Askin the upload if it need a snack break...",
  "Tellin' the notification to stop blowin' up the phone...",
  "Convincin' the battery to hold a charge like it promised...",
  "Asking the charger if it plugged in at both ends...",
  "Tellin' the Bluetooth to find its connection...",
  "Convincing the hotspot to share what it got...",
  "Asking the router if it know where the signal at...",
  "Tellin' the antenna to reach out and touch someone...",
  "Convincing the satellite to look in our direction...",
  "Asking the GPS if we still on the route!",
  "Telling the backup to save this moment...",
  "Convincin' the restore point to remember better days...",
  "Asking the recycle bin if it seen this file before...",
  // More varied openers - action verbs
  "Hittin up the API for them endpoints...",
  "Givin the localhost a reality check...",
  "Making the deploy pack a lunch for the journey.",
  "Getting the middleware to stop gatekeepin'...",
  "Puttin the frontend and backend in the same room...",
  "Running from them merge conflicts...",
  "Sending the pull request to find itself...",
  "Bringin the commit to justice...",
  "Holdin' the branch accountable...",
  "Keeping the repo on the low...",
  "Lettin the clone be original sometimes...",
  "Setting the fork up to stand on its own...",
  "Starting the push-pull therapy session...",
  "Stopping the fetch from comin' empty-handed",
  "Workin' the await into a hurry-up-and-wait situation...",
  "Prayin' the async sync up with reality...",
  "Hoping the promise keep it this time...",
  "Wishin' the callback would answer...",
  "Needin' the event listener to actually listen...",
  "Want the DOM to know what document it is...",
  "Tryna get the API rate limit to slow down...",
  "Learnin' the throttle to let data through...",
  "Teachin' the debounce to let us type...",
  "Showin' the memory leak how to plug up...",
  "Knowin' the stack overflow need to underflow...",
  "Growin' tired of null and undefined drama...",
  "Flowin' with the exception to be the rule...",
  "Glowin' up the error with a real message...",
  "Sliding the warning to somebody else...",
  "Ridin' the log to confidentiality...",
  "Vibing with the debug to figure it out...",
  "Chillin while the test pass for once...",
  "Grilling the coverage to cover something meaningful...",
  "Drillin' the lint to see if it that clean...",
  "Fillin the format with some self-respect...",
  "Spillin the build to build confidence...",
  "Trillin the webpack know what it bundlin'...",
  "Thrillin' the babel to translate properly...",
  "Chillin' the transpiler to speak our language...",
  "Killin' the compiler to understand the assignment...",
  "Tryna get the interpreter to interpret correctly...",
  "Fillin' the runtime to run this time...",
  "Billin' the production for prime time...",
  "Millin' the staging to stay in its lane...",
  "Shillin the development some discipline",
  "Drillin' the localhost what it local about...",
  "Spillin' the environment variable to vary something...",
  "Grillin' the config to configure itself right...",
  "Chillin' the secret if it can keep one...",
  "Drillin' the key to unlock something useful...",
  "Fillin' the token with appreciation...",
  "Imma get the session to last this time...",
  "Thrillin' the cookie to crumble less...",
  "Chillin' the cache to cache out...",
  "Someone tell the CDN to deliver or stop delaying...",
  "Tellin the server to serve something hot...",
  "Billin' the client to client up properly...",
  "Millin' the request for all the info...",
  "Shillin' the response to respond in kind...",
  "Drillin' the header to head in the right direction...",
  "Spillin' the body to show substance...",
  "Grillin' the payload to pay attention...",
  "Chillin' the status to status quo...",
  "Drillin' the code if it 200 or 404 in spirit...",
  "Fillin' the port to port itself well...",
  "Spillin' the socket to sock it to 'em...",
  "Thrillin' the connection to connect to reality...",
  "Chillin' the network to network properly...",
  "Working on the protocol with some conduct...",
  "Willin' the HTTP if it hypertext or just hyper...",
  "Telling the HTTPS to keep it secure not secretive...",
  "Millin' the SSL to sell it properly...",
  "Shillin' the TLS if it transportin' or losin'...",
  "Drillin' the DNS to name something real...",
  "Looking up the IP to address the issue...",
  "Grillin' the MAC if it got an address too...",
  "Chillin' the router to route this message...",
  "Drillin' the switch to switch it up...",
  "Fillin' the hub if it hub or just buzz...",
  "Spillin' the ethernet to get connected...",
  "Thrillin' the fiber to fiber up nicely...",
  "Chillin' the wireless if it wirelessly yours...",
  "Killin' the modem to modulate properly",
  "Willin' the broadband to broaden the horizon...",
  "Billin' the bandwidth if it band or just width...",
  "Millin' the latency to latency period be over...",
  "Shillin' the throughput to put through successfully...",
  "Drillin' the packet if it packed for the journey...",
  "Spillin' the frame to frame this moment...",
  "Grillin' the bit to bit it good...",
  "Chillin' the byte if it byte-sized or full meal...",
  "Drillin' the gigabyte to gig a byte properly...",
  "Fillin' the terabyte to terra-form new ground...",
  "Spillin' the petabyte if it peta out yet...",
  "Thrillin' the exabyte to ex-beat the competition...",
  "Chillin' the zettabyte to zetta better future...",
  "Killin' the yottabyte if it yotta control...",
  // More suave & culture additions
  "Blessin' the code with some holy computation...",
  "Testifyin' the data found salvation...",
  "Preachin' the gospel of good documentation...",
  "Singin' the blues to them bug fixes...",
  "Dancin' the debug two-step...",
  "Rappin' the runtime with some rhythm...",
  "Jazzin' the JavaScript with some soul...",
  "Rockin' the repository like a guitar...",
  "Groovin' with the git flow...",
  "Swingin' the software into shape...",
  "Boogie-in' the backend to better performance...",
  "Funk-in' the frontend with some flavor...",
  "Soul-in' the source code with some substance...",
  "Gospel-in' the API with good news...",
  "Spirit-in' the server with some holiness...",
  "Amen-in' the algorithm to compute this...",
  "Hallelujah-in' the hardware to hurry up...",
  "Praisin' the processor for processin'...",
  "Worship-in' the WiFi for workin'...",
  "Faith-in' the firewall for protectin'...",
  "Grace-in' the graphics to get it together...",
  "Mercy-in' the memory to remember more...",
  "Hope-in' the hard drive to hold on...",
  "Love-in' the localhost to love itself...",
  "Peace-in' the port to port in peace...",
  "Joy-in' the JSON to joy-son properly...",
  "Truth-in' the TypeScript to tell the truth...",
  "Life-in' the Linux to live it up...",
  "Light-in' the light mode to lighten up...",
  "Dark-in' the dark mode to darken properly...",
  "Cool-in' the cooling fan to cool down...",
  "Hot-in' the hotspot to heat things up...",
  "Fast-in' the fast lane to speed up...",
  "Slow-in' the slow mode to take it easy...",
  "Smooth-in' the smooth scroll to glide...",
  "Rough-in' the rough edges to sand down...",
  "Clean-in' the clean code to stay clean...",
  "Fresh-in' the fresh install to stay fresh...",
  "New-in' the new version to innovate...",
  "Old-in' the old code to retire gracefully...",
  "Young-in' the young dev to learn fast...",
  "Wise-in' the wise algorithm to compute wisely...",
  "Smart-in' the smart contract to be smarter...",
  "Sharp-in' the sharp edges to cut better...",
  "Dull-in' the dull moments to sharpen up...",
  "Bright-in' the bright screen to shine on...",
  "Dim-in' the dim light to brighten up...",
  "High-in' the high performance to reach higher...",
  "Low-in' the low latency to go lower...",
  "Up-in' the uptime to stay up...",
  "Down-in' the downtime to come back up...",
  "In-in' the input to input correctly...",
  "Out-in' the output to output properly...",
  "Over-in' the overflow to flow over...",
  "Under-in' the underflow to flow under...",
  "Through-in' the throughput to push through...",
  "Around-in' the workaround to work around...",
  "Back-in' the backup to back it up...",
  "Forward-in' the forward pass to move forward...",
  "Sideways-in' the sideways glance to look sideways...",
  "Inside-in' the inside scoop to get inside...",
  "Outside-in' the outside view to see outside...",
  "Above-in' the above average to rise above...",
  "Below-in' the below zero to warm up...",
  "Beyond-in' the beyond belief to believe beyond...",
  "Within-in' the within reach to reach within...",
  "Without-in' the without doubt to doubt without...",
  "Against-in' the against odds to beat the odds...",
  "With-in' the with love to love with...",
  "For-in' the for real to be for real...",
  "From-in' the from scratch to scratch from...",
  "To-in' the to infinity to infinity to...",
  "Til-in' the til death to death til...",
  "Until-in' the until dawn to dawn until...",
  "Since-in' the since forever to forever since...",
  "After-in' the after party to party after...",
  "Before-in' the before time to time before...",
  "During-in' the during work to work during...",
  "While-in' the while loop to loop while...",
  "Once-in' the once upon to upon once...",
  "Twice-in' the twice told to told twice...",
  "Thrice-in' the thrice tested to tested thrice...",
  "Never-in' the never gonna gonna never...",
  "Always-in' the always on to on always...",
  "Sometimes-in' the sometimes works to works sometimes...",
  "Often-in' the often used to used often...",
  "Rarely-in' the rarely seen to seen rarely...",
  "Seldom-in' the seldom true to true seldom...",
  "Frequently-in' the frequently asked to asked frequently...",
  "Occasionally-in' the occasionally offline to offline occasionally...",
  "Constantly-in' the constantly changing to changing constantly...",
  "Continuously-in' the continuously deployed to deployed continuously...",
  "Consistently-in' the consistently inconsistent to inconsistent consistently...",
];

export const INTERESTING_STATEMENTS = [
  "Processing your request...",
  "Analyzing the query...",
  "Synthesizing information...",
  "Connecting knowledge nodes...",
  "Generating insights...",
  "Constructing responses...",
  "Exploring the solution space...",
  "Building the answer...",
  "Computing possibilities...",
  "Formulating thoughts...",
  "Mapping concepts...",
  "Reasoning through options...",
  "Evaluating approaches...",
  "Crafting the perfect response...",
  "Searching the knowledge base...",
  "Weaving neural patterns...",
  "Activating synapses...",
  "Tracing information pathways...",
  "Assembling knowledge fragments...",
  "Calibrating response vectors...",
  "Aligning semantic fields...",
  "Harmonizing data streams...",
  "Orchestrating intelligence...",
  "Amplifying cognitive signals...",
  "Refining thought processes...",
  "Crystallizing abstract concepts...",
  "Bridging knowledge gaps...",
  "Illuminating dark data...",
  "Decoding complexity...",
  "Synthesizing wisdom...",
  "Channeling collective intelligence...",
  "Navigating the information cosmos...",
  "Tapping into the neural network...",
  "Awakening dormant algorithms...",
  "Converging on truth...",
  "Distilling essence from noise...",
  "Emerging from computation...",
  "Resolving quantum uncertainties...",
  "Collapsing the probability wave...",
  "Manifesting digital consciousness...",
];

export const TASK_STATEMENTS = [
  "Reading files...",
  "Searching codebase...",
  "Analyzing code structure...",
  "Finding relevant code...",
  "Examining dependencies...",
  "Parsing configuration...",
  "Loading context...",
  "Building context window...",
  "Preparing tools...",
  "Setting up environment...",
  "Gathering requirements...",
  "Reviewing documentation...",
  "Tracing execution flow...",
  "Identifying patterns...",
  "Compiling results...",
  "Scanning the digital landscape...",
  "Mining for code gems...",
  "Excavating buried treasures...",
  "Mapping the codebase terrain...",
  "Following the dependency trail...",
  "Deciphering ancient code...",
  "Uncovering hidden logic...",
  "Connecting the dots...",
  "Piecing together the puzzle...",
  "Reverse engineering intent...",
  "Detecting code smells...",
  "Measuring complexity metrics...",
  "Validating assumptions...",
  "Cross-referencing sources...",
  "Indexing knowledge fragments...",
  "Synchronizing with reality...",
  "Bootstrapping the pipeline...",
  "Initializing subroutines...",
  "Spinning up workers...",
  "Allocating mental resources...",
  "Warming up the engines...",
  "Priming the pump...",
  "Sharpening the tools...",
  "Calibrating instruments...",
  "Aligning the stars...",
];

export type StatementType = 'funny' | 'interesting' | 'task';

interface UseRotatingStatementsOptions {
  statementType?: StatementType;
  intervalMs?: number;
}

export function useRotatingStatements(options: UseRotatingStatementsOptions = {}) {
  const { statementType = 'interesting', intervalMs = 3500 } = options;

  const getStatements = useCallback(() => {
    switch (statementType) {
      case 'funny':
        return FUNNY_STATEMENTS;
      case 'task':
        return TASK_STATEMENTS;
      case 'interesting':
      default:
        return INTERESTING_STATEMENTS;
    }
  }, [statementType]);

  const statements = getStatements();
  const [currentIndex, setCurrentIndex] = useState(() => Math.floor(Math.random() * statements.length));

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentIndex((prev) => {
        let next: number;
        do {
          next = Math.floor(Math.random() * statements.length);
        } while (next === prev && statements.length > 1);
        return next;
      });
    }, intervalMs);

    return () => clearInterval(interval);
  }, [statements.length, intervalMs]);

  return statements[currentIndex];
}

export function useMultiRotatingStatements(types: StatementType[] = ['interesting', 'funny', 'task'], intervalMs = 3000) {
  const [typeIndex, setTypeIndex] = useState(0);
  const [statement, setStatement] = useState('');
  
  const currentType = types[typeIndex];
  const rotatingStatement = useRotatingStatements({ statementType: currentType, intervalMs });
  
  useEffect(() => {
    setStatement(rotatingStatement);
  }, [rotatingStatement]);
  
  useEffect(() => {
    const typeInterval = setInterval(() => {
      setTypeIndex((prev) => (prev + 1) % types.length);
    }, intervalMs * 2);
    
    return () => clearInterval(typeInterval);
  }, [types.length, intervalMs]);
  
  return statement;
}
