/**
 * Replicate Image Generation Provider
 * Uses Replicate API for various image generation models (SDXL, Flux, etc.)
 * Documentation: https://replicate.com/docs
 */

import Replicate from 'replicate';
import type {
  ImageGenerationProvider,
  ImageGenerationParams,
  ImageGenerationResponse,
  GeneratedImage,
  ProviderConfig,
  ProviderCapabilities,
  ImageGenerationError,
  ImageGenerationErrorType,
  AspectRatio,
} from '../types';
import { ASPECT_RATIO_DIMENSIONS, QUALITY_PRESETS, ImageGenerationErrorType as ErrorType } from '../types';

export interface ReplicateProviderConfig extends ProviderConfig {
  defaultModel?: string;
}

export class ReplicateImageProvider implements ImageGenerationProvider {
  readonly id = 'replicate';
  readonly name = 'Replicate';
  readonly defaultModel = 'stability-ai/stable-diffusion-xl-base-1.0';

  private client: Replicate | null = null;
  private apiKey?: string;
  private _defaultModel: string = this.defaultModel;

  readonly models = [
    'stability-ai/stable-diffusion-xl-base-1.0',
    'black-forest-labs/flux-schnell',
    'stability-ai/stable-diffusion-3.5-large',
    'stability-ai/stable-diffusion-2-1',
    'runwayml/stable-diffusion-v1-5',
    'prompthero/openjourney',
    'Lykon/DreamShaper',
  ];

  readonly capabilities: ProviderCapabilities = {
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:2', '2:3', '21:9'],
    resolutions: [
      { width: 1024, height: 1024 },
      { width: 1280, height: 720 },
      { width: 720, height: 1280 },
      { width: 1152, height: 864 },
      { width: 1152, height: 768 },
      { width: 768, height: 1152 },
      { width: 1344, height: 576 },
      { width: 768, height: 768 },
      { width: 1024, height: 768 },
      { width: 768, height: 1024 },
    ],
    supportsNegativePrompt: true,
    supportsImg2Img: true,
    supportsSeed: true,
    supportsBatchGeneration: true,
    supportsSamplers: true,
    maxBatchSize: 4,
    stylePresets: [
      'None',
      'Photorealistic',
      'Anime',
      'Digital Art',
      'Oil Painting',
      'Watercolor',
      'Sketch',
      '3D Render',
      'Pixel Art',
      'Concept Art',
    ],
    qualityPresets: ['low', 'medium', 'high', 'ultra'],
  };

  initialize(config: ReplicateProviderConfig): void {
    this.apiKey = config.apiKey;
    if (config.defaultModel) {
      this._defaultModel = config.defaultModel;
    }
    
    if (this.apiKey) {
      this.client = new Replicate({ auth: this.apiKey });
    }
  }

  async isAvailable(): Promise<boolean> {
    if (!this.client || !this.apiKey) {
      return false;
    }

    try {
      // ✅ FIX 3: Actually test API connectivity instead of always returning true
      // Try to list models to verify API access (get requires model name which may not exist)
      await this.client.models.list();
      return true;
    } catch (error) {
      console.warn('[ReplicateProvider] Health check failed:', error instanceof Error ? error.message : error);
      return false;
    }
  }

  async generate(
    params: ImageGenerationParams,
    signal?: AbortSignal
  ): Promise<ImageGenerationResponse> {
    if (!this.client) {
      throw this.createError(
        'Replicate provider not initialized. Please check your API key.',
        ErrorType.NOT_CONFIGURED
      );
    }

    const startTime = Date.now();
    const model = params.extra?.model || this._defaultModel;

    try {
      // Apply aspect ratio if specified
      const { width, height } = this.resolveDimensions(params);
      
      // Apply quality preset if specified
      const { steps, guidance } = this.resolveQualitySettings(params);

      // Build input based on model
      const input = this.buildModelInput(model, params, width, height, steps, guidance);

      // Run the model
      const output = await this.client.run(model, { input, signal }) as any;

      // Normalize output into image URLs
      const images = this.normalizeOutput(output, width, height, model, startTime);

      if (images.length === 0) {
        throw this.createError(
          'No images were generated by the model',
          ErrorType.GENERATION_FAILED
        );
      }

      const generationTime = Date.now() - startTime;

      return {
        success: true,
        images,
        provider: this.id,
        model,
        usage: {
          credits: images.length, // Approximate
        },
      };
    } catch (error) {
      if (error instanceof Error) {
        if (error.name === 'AbortError') {
          throw this.createError('Image generation timed out', ErrorType.TIMEOUT, error);
        }

        if (error.message.includes('429') || error.message.includes('rate limit')) {
          throw this.createError(
            'Rate limit exceeded. Please try again later.',
            ErrorType.RATE_LIMITED,
            error
          );
        }

        if (error.message.includes('401') || error.message.includes('authentication')) {
          throw this.createError(
            'Authentication failed. Please check your Replicate API key.',
            ErrorType.AUTH_FAILED,
            error
          );
        }

        throw this.createError(
          `Image generation failed: ${error.message}`,
          ErrorType.GENERATION_FAILED,
          error
        );
      }

      throw this.createError(
        'Unknown error during image generation',
        ErrorType.GENERATION_FAILED
      );
    }
  }

  getDefaultParams(): Partial<ImageGenerationParams> {
    return {
      width: 1024,
      height: 1024,
      steps: 28,
      guidance: 5.5,
      numImages: 1,
      quality: 'medium',
    };
  }

  /**
   * Resolve dimensions from aspect ratio or explicit width/height
   */
  private resolveDimensions(params: ImageGenerationParams): { width: number; height: number } {
    if (params.aspectRatio) {
      return ASPECT_RATIO_DIMENSIONS[params.aspectRatio];
    }
    return {
      width: params.width || 1024,
      height: params.height || 1024,
    };
  }

  /**
   * Resolve steps and guidance from quality preset
   */
  private resolveQualitySettings(params: ImageGenerationParams): { steps: number; guidance: number } {
    if (params.quality && QUALITY_PRESETS[params.quality]) {
      return QUALITY_PRESETS[params.quality];
    }
    return {
      steps: params.steps || 28,
      guidance: params.guidance || 5.5,
    };
  }

  /**
   * Build model-specific input parameters
   */
  private buildModelInput(
    model: string,
    params: ImageGenerationParams,
    width: number,
    height: number,
    steps: number,
    guidance: number
  ): Record<string, any> {
    const input: Record<string, any> = {
      prompt: params.prompt,
    };

    // Model-specific parameter mapping
    const modelId = model.toLowerCase();

    // Common parameters
    if (params.negativePrompt) {
      input['negative_prompt'] = params.negativePrompt;
    }

    input['width'] = width;
    input['height'] = height;
    input['num_inference_steps'] = steps;
    input['guidance_scale'] = guidance;

    // Seed
    if (typeof params.seed === 'number') {
      input['seed'] = params.seed;
    }

    // Image-to-image
    if (params.initImage) {
      input['image'] = params.initImage;
      if (params.imageStrength !== undefined) {
        input['image_strength'] = params.imageStrength;
        input['prompt_strength'] = 1 - params.imageStrength;
      }
    }

    // Batch generation
    if (params.numImages && params.numImages > 1) {
      input['num_images'] = params.numImages;
      input['num_outputs'] = params.numImages;
    }

    // Sampler (model-dependent)
    if (params.sampler) {
      input['sampler'] = params.sampler;
      input['scheduler'] = params.sampler;
    }

    // Model-specific adjustments
    if (modelId.includes('flux')) {
      // Flux uses different parameter names
      input['go_fast'] = true;
      input['megapixels'] = '1';
      delete input['num_inference_steps'];
      input['num_inference_steps'] = steps;
    }

    if (modelId.includes('stable-diffusion-3')) {
      input['aspect_ratio'] = this.getAspectRatioPreset(params.aspectRatio);
    }

    return input;
  }

  /**
   * Get aspect ratio preset string for models that support it
   */
  private getAspectRatioPreset(aspectRatio?: AspectRatio): string {
    if (!aspectRatio) return '1:1';
    const mapping: Record<AspectRatio, string> = {
      '1:1': '1:1',
      '16:9': '16:9',
      '9:16': '9:16',
      '4:3': '4:3',
      '3:2': '3:2',
      '2:3': '2:3',
      '21:9': '21:9',
    };
    return mapping[aspectRatio];
  }

  /**
   * Normalize various output formats to GeneratedImage array
   */
  private normalizeOutput(
    output: any,
    width: number,
    height: number,
    model: string,
    startTime: number
  ): GeneratedImage[] {
    const images: GeneratedImage[] = [];
    const generationTime = Date.now() - startTime;

    // Handle array output (most common)
    if (Array.isArray(output)) {
      for (const url of output.filter((u) => typeof u === 'string')) {
        images.push({
          url,
          width,
          height,
          metadata: {
            model,
            provider: this.id,
            generationTime,
          },
        });
      }
    }
    // Handle object output
    else if (output && typeof output === 'object') {
      if (Array.isArray(output.output)) {
        for (const url of output.output) {
          if (typeof url === 'string') {
            images.push({ url, width, height, metadata: { model, provider: this.id, generationTime } });
          }
        }
      } else if (typeof output.image === 'string') {
        images.push({ url: output.image, width, height, metadata: { model, provider: this.id, generationTime } });
      } else if (typeof output.url === 'string') {
        images.push({ url: output.url, width, height, metadata: { model, provider: this.id, generationTime } });
      } else if (typeof output.images === 'string') {
        // Some models return comma-separated URLs
        const urls = output.images.split(',').map((u: string) => u.trim());
        for (const url of urls) {
          images.push({ url, width, height, metadata: { model, provider: this.id, generationTime } });
        }
      }
    }

    return images;
  }

  /**
   * Create a standardized error
   */
  private createError(
    message: string,
    type: ImageGenerationErrorType,
    originalError?: Error
  ): ImageGenerationError {
    const error = new Error(message) as ImageGenerationError;
    error.name = 'ImageGenerationError';
    (error as any).type = type;
    (error as any).provider = this.id;
    (error as any).originalError = originalError;
    return error;
  }
}
