/**
 * Vercel AI Image Generation Provider
 * Uses Vercel's image generation models via OpenAI-compatible API
 */

import { createOpenAI } from '@ai-sdk/openai';
import type {
  ImageGenerationProvider,
  ImageGenerationParams,
  ImageGenerationResponse,
  GeneratedImage,
  ProviderConfig,
  ProviderCapabilities,
  ImageGenerationError,
  ImageGenerationErrorType,
} from '../types';
import { ImageGenerationErrorType as ErrorType } from '../types';

export class VercelImageProvider implements ImageGenerationProvider {
  readonly id = 'vercel';
  readonly name = 'Vercel AI';
  readonly defaultModel = 'flux-pro-1.1';
  
  private client: any = null;
  private apiKey?: string;
  private baseURL?: string;

  readonly models = [
    'flux-pro-1.1',
    'flux-pro-1.1-ultra',
    'flux-2-pro',
    'flux-2-max',
    'flux-kontext-pro',
    'flux-kontext-max',
    'imagen-4.0',
    'imagen-4.0-ultra',
    'imagen-4.0-fast',
    'gpt-image-2',
    'gpt-image-1.5',
    'gpt-image-1',
    'gpt-image-1-mini',
  ];

  readonly capabilities: ProviderCapabilities = {
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:2', '2:3', '21:9'],
    resolutions: [
      { width: 1024, height: 1024 },
      { width: 1280, height: 720 },
      { width: 720, height: 1280 },
      { width: 1152, height: 864 },
      { width: 1152, height: 768 },
      { width: 768, height: 1152 },
      { width: 1344, height: 576 },
    ],
    supportsNegativePrompt: true,
    supportsImg2Img: false,
    supportsSeed: true,
    supportsBatchGeneration: true,
    supportsSamplers: false,
    maxBatchSize: 4,
    stylePresets: ['None', 'Photorealistic', 'Anime', 'Digital Art', 'Oil Painting', 'Watercolor', 'Sketch', '3D Render'],
    qualityPresets: ['low', 'medium', 'high', 'ultra'],
  };

  initialize(config: ProviderConfig): void {
    this.apiKey = config.apiKey;
    this.baseURL = config.baseURL;
    
    if (this.apiKey) {
      this.client = createOpenAI({
        apiKey: this.apiKey,
        baseURL: this.baseURL || 'https://api.vercel.com/v1',
      });
    }
  }

  async isAvailable(): Promise<boolean> {
    if (!this.client || !this.apiKey) {
      return false;
    }
    
    try {
      // Simple API call to check availability
      await this.client.models.list();
      return true;
    } catch {
      return false;
    }
  }

  async generate(
    params: ImageGenerationParams,
    signal?: AbortSignal
  ): Promise<ImageGenerationResponse> {
    if (!this.client) {
      throw this.createError(
        'Vercel provider not initialized. Please check your VERCEL_API_KEY environment variable.',
        ErrorType.NOT_CONFIGURED
      );
    }

    console.log('[VercelProvider] Starting image generation with prompt:', params.prompt.substring(0, 100));

    const startTime = Date.now();
    const controller = new AbortController();

    if (signal) {
      signal.addEventListener('abort', () => controller.abort());
    }

    try {
      // Build the image generation request
      const model = params.extra?.model as string || this.defaultModel;
      const quality = params.quality || 'high';
      const size = this.getSizeForQuality(quality);
      const numImages = Math.min(params.numImages || 1, this.capabilities.maxBatchSize);

      console.log('[VercelProvider] Generating', numImages, 'image(s) with model:', model, 'size:', size);

      const response = await this.client.images.generate({
        model,
        prompt: this.buildPrompt(params),
        negative_prompt: params.negativePrompt,
        n: numImages,
        size: size,
        quality: quality,
        seed: typeof params.seed === 'number' ? params.seed : undefined,
        response_format: 'url',
      }, {
        signal: controller.signal,
      });

      console.log('[VercelProvider] Got response with', response.data?.length || 0, 'images');

      if (!response.data || response.data.length === 0) {
        throw this.createError(
          'No images were generated by the Vercel API',
          ErrorType.GENERATION_FAILED
        );
      }

      // Convert response to our standard format
      const images: GeneratedImage[] = response.data.map((item: any) => ({
        url: item.url,
        width: this.getWidthForSize(size),
        height: this.getHeightForSize(size),
        seed: item.seed,
        metadata: {
          model: model,
          provider: this.id,
          quality: quality,
          size: size,
          revised_prompt: item.revised_prompt,
        },
      }));

      const duration = Date.now() - startTime;
      console.log(`[VercelProvider] Successfully generated ${images.length} image(s) in ${duration}ms`);

      return {
        success: true,
        images,
        provider: this.id,
        model: model,
        usage: {
          credits: images.length,
        },
      };
    } catch (error) {
      const duration = Date.now() - startTime;
      console.error(`[VercelProvider] Error after ${duration}ms:`, error);

      if (error instanceof Error) {
        if (error.name === 'AbortError' || error.message.includes('aborted')) {
          throw this.createError(
            'Image generation timed out',
            ErrorType.TIMEOUT
          );
        }

        if (error.message.includes('429') || error.message.includes('rate limit')) {
          throw this.createError(
            'Rate limit exceeded. Please try again later.',
            ErrorType.RATE_LIMITED,
            error
          );
        }

        if (error.message.includes('401') || error.message.includes('403') || error.message.includes('unauthorized')) {
          throw this.createError(
            'Authentication failed. Please check your Vercel API key.',
            ErrorType.AUTH_FAILED,
            error
          );
        }

        if (error.message.includes('Invalid model') || error.message.includes('model not found')) {
          throw this.createError(
            `Model ${params.extra?.model || this.defaultModel} is not available or not supported by Vercel.`,
            ErrorType.INVALID_MODEL,
            error
          );
        }

        throw this.createError(
          `Image generation failed: ${error.message}`,
          ErrorType.GENERATION_FAILED,
          error
        );
      }

      throw this.createError(
        'Unknown error during image generation',
        ErrorType.GENERATION_FAILED
      );
    }
  }

  getDefaultParams(): Partial<ImageGenerationParams> {
    return {
      width: 1024,
      height: 1024,
      numImages: 1,
      quality: 'high',
    };
  }

  private buildPrompt(params: ImageGenerationParams): string {
    let prompt = params.prompt;

    // Add quality modifiers
    if (params.quality) {
      const qualityModifiers: Record<string, string> = {
        low: '',
        medium: ', high quality',
        high: ', highly detailed, professional quality, sharp focus',
        ultra: ', ultra detailed, masterpiece, best quality, professional photography, 8k resolution',
      };
      if (qualityModifiers[params.quality]) {
        prompt += qualityModifiers[params.quality];
      }
    }

    // Add aspect ratio context
    if (params.aspectRatio) {
      const ratioHints: Record<string, string> = {
        '1:1': '',
        '16:9': ', cinematic widescreen composition',
        '9:16': ', vertical portrait composition, perfect for mobile',
        '4:3': ', classic photography composition',
        '3:2': ', landscape photography format',
        '2:3': ', portrait photography format',
        '21:9': ', ultrawide cinematic composition',
      };
      if (ratioHints[params.aspectRatio]) {
        prompt += ratioHints[params.aspectRatio];
      }
    }

    // Add style context
    if (params.style && params.style !== 'None') {
      prompt += `, ${params.style} artistic style`;
    }

    return prompt;
  }

  private getSizeForQuality(quality: string): string {
    // Map quality to Vercel image sizes
    const qualityToSize: Record<string, string> = {
      low: '512x512',
      medium: '768x768',
      high: '1024x1024',
      ultra: '1792x1024',
    };
    return qualityToSize[quality] || '1024x1024';
  }

  private getWidthForSize(size: string): number {
    const [width] = size.split('x').map(Number);
    return width || 1024;
  }

  private getHeightForSize(size: string): number {
    const [, height] = size.split('x').map(Number);
    return height || 1024;
  }

  private createError(
    message: string,
    type: ImageGenerationErrorType,
    originalError?: Error
  ): ImageGenerationError {
    const error = new Error(message) as ImageGenerationError;
    error.name = 'ImageGenerationError';
    (error as any).type = type;
    (error as any).provider = this.id;
    (error as any).originalError = originalError;
    return error;
  }
}